FROM ubuntu:latest

# Install necessary packages
RUN apt update && apt install -y ansible openssh-client && \
    mkdir -p /root/.ssh && \
    chmod 700 /root/.ssh

# Copy the SSH private key and ensure correct permissions
COPY ssh-keys/id_rsa /root/.ssh/id_rsa
RUN chmod 600 /root/.ssh/id_rsa

# Allow SSH connections without strict host key checking
RUN echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config

# Keep the container running
CMD ["tail", "-f", "/dev/null"]

